window.PRODUCTS = [
  {"id":"gissah-imperial-valley","brand":"Gissah","name":"Imperial Valley","size":"200ml","gender":"Unisex","family":"Amber Woody","price":399,"compareAt":429,"badge":"Hero pick","top":["Davana","Italian Bergamot","Pink Pepper"],"heart":["White Amber","African Rosemary","Oud"],"base":["Musk","Leather","Vetiver Haiti"],"accent":"amber","source":"https://sa.gissah.com/shop/g00093-imperial-valley-200ml-1751","copy":"A bold oud-led signature with bright spice up top and a polished leather-musk drydown."},
  {"id":"gissah-mavro","brand":"Gissah","name":"Mavro","size":"200ml","gender":"Men","family":"Woody Spicy Citrus","price":399,"compareAt":429,"badge":"For him","top":["Bergamot","Grapefruit","Lemon","Pink Pepper"],"heart":["Praline","Saffron"],"base":["Cedarwood","Patchouli","Tonka"],"accent":"smoke","source":"https://sa.gissah.com/shop/mavro-2286","copy":"Citrus and pink pepper sharpen a sweet saffron heart before cedar, patchouli and tonka settle in."},
  {"id":"gissah-akoya","brand":"Gissah","name":"Akoya","size":"200ml","gender":"Unisex","family":"Citrus Woody","price":399,"compareAt":429,"badge":"Crowd pleaser","top":["Bergamot","Orange","Raspberry"],"heart":["Caramel","Lavender","Jasmine"],"base":["Leatherwood","Patchouli","Sandalwood"],"accent":"berry","source":"https://sa.gissah.com/shop/akoya-2280","copy":"Bright fruit, soft caramel and florals over a warm woody-leather base. Easy to recommend, easy to wear."},
  {"id":"reef-11","brand":"REEF","name":"REEF 11","size":"100ml","gender":"Unisex","family":"Spicy Floral Woody","price":369,"compareAt":399,"badge":"Best seller","top":["Pink Pepper"],"heart":["Jasmine"],"base":["Sandalwood"],"accent":"sand","source":"https://usa.reefperfumes.com/products/reef-11-perfume","copy":"A simple, confident three-note structure: pink pepper, jasmine and sandalwood."},
  {"id":"reef-15","brand":"REEF","name":"REEF 15","size":"100ml","gender":"Men","family":"Citrus Floral Oud","price":369,"compareAt":399,"badge":"Fresh oud","top":["Bergamot"],"heart":["Convallaria"],"base":["Oud Sidr"],"accent":"olive","source":"https://usa.reefperfumes.com/products/reef-15-perfume","copy":"Fresh bergamot transitions into a clean floral heart, then deepens into warm sidr oud."},
  {"id":"reef-19","brand":"REEF","name":"REEF 19","size":"100ml","gender":"Unisex","family":"White Floral Musk","price":369,"compareAt":399,"badge":"Clean floral","top":["Lily of the Valley"],"heart":["Jasmine"],"base":["White Musk"],"accent":"pearl","source":"https://usa.reefperfumes.com/products/reef-19-perfume","copy":"Soft white florals and white musk for customers who want a cleaner, more understated signature."},
  {"id":"osma-noir","brand":"OSMA","name":"OSMA Noir","size":"100ml","gender":"Unisex","family":"Saffron Aromatic Oud","price":269,"compareAt":299,"badge":"Deep oud","top":["Indian Saffron"],"heart":["Rosemary"],"base":["Oud"],"accent":"noir","source":"https://osmaperfumes.com/en/osma-noir-perfume/p1276468672","copy":"A dark, restrained oud profile: warm saffron, green rosemary and a deep woody finish."},
  {"id":"osma-o","brand":"OSMA","name":"OSMA O","size":"150ml","gender":"Unisex","family":"Fruity Tobacco Musk","price":299,"compareAt":329,"badge":"Statement","top":["Pear"],"heart":["Tobacco"],"base":["Musk"],"accent":"copper","source":"https://osmaperfumes.com/en/osma-o-perfume/p201096472","copy":"Juicy pear meets tobacco and musk, giving the collection a richer, more contemporary option."},
  {"id":"osma-breez","brand":"OSMA","name":"OSMA Breez","size":"150ml","gender":"Unisex","family":"Floral Gourmand","price":299,"compareAt":329,"badge":"Soft gourmand","top":["Coconut"],"heart":["Soft Florals"],"base":["Praline"],"accent":"cream","source":"https://osmaperfumes.com/en/osma-breez-perfume/p1684653030","copy":"Creamy coconut and florals settle into praline. A softer gourmand for everyday wear."},
  {"id":"mold-oriental","brand":"MOLD","name":"Oriental","size":"100ml","gender":"Unisex","family":"Aromatic Gourmand","price":169,"compareAt":199,"badge":"Value pick","top":["Lavender"],"heart":["Vanilla"],"base":["Tonka Bean"],"accent":"violet","source":"https://moldperfume.com/en/long-lasting-perfume-mold-oriental/p1159953528","copy":"Lavender, vanilla and tonka create an approachable warm scent with broad gifting appeal."},
  {"id":"mold-miss-vanilla","brand":"MOLD","name":"Miss Vanilla","size":"100ml","gender":"Women","family":"Citrus Woody Spicy","price":169,"compareAt":199,"badge":"Sweet citrus","top":["Orange"],"heart":["Sandalwood"],"base":["Cardamom"],"accent":"vanilla","source":"https://moldperfume.com/en/%D8%A8%D8%AE%D8%A7%D8%AE-%D9%85%D9%8A%D8%B3-%D9%81%D8%A7%D9%86%D9%8A%D9%84%D8%A7-%D8%B9%D8%B7%D8%B1-%D8%A8%D8%B1%D8%AA%D9%82%D8%A7%D9%84-%D9%85%D9%86%D8%B9%D8%B4-%D9%88%D8%AE%D8%B4%D8%A8-%D8%A7%D9%84%D8%B5%D9%86%D8%AF%D9%84-100-%D9%85%D9%84/p1330512275","copy":"Fresh orange, warm sandalwood and cardamom make this a friendly entry point into Arabian fragrance."},
  {"id":"mold-clock","brand":"MOLD","name":"CLOCK","size":"100ml","gender":"Men","family":"Spicy Leather","price":169,"compareAt":199,"badge":"Bold leather","top":["Peruvian Pepper"],"heart":["Kashmiri Pepper"],"base":["Leather"],"accent":"steel","source":"https://moldperfume.com/en/long-lasting-spray-mold-clock/p237846526","copy":"Pepper-on-pepper intensity over leather. Strong personality and a clear masculine positioning."}
];
